services:
  - type: web
    name: comprix-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.20.7
      - key: DATABASE_URL
        value: file:/data/dev.db
